2022-01-14 18:40:37.559 [main] ERROR com.kaa.simplebuild.DataProviderJDBC - org.h2.jdbc.JdbcSQLException: Соединение разорвано: "java.net.ConnectException: Connection refused: no further information: localhost"
Connection is broken: "java.net.ConnectException: Connection refused: no further information: localhost" [90067-195]
2022-01-14 18:40:37.572 [main] ERROR com.kaa.simplebuild.DataProviderJDBC - java.lang.NullPointerException
2022-01-14 18:41:12.570 [main] INFO  com.kaa.simplebuild.DataProviderJDBC - prep0: INSERT INTO ROOFMATERIAL VALUES (?,?,?) {1: 1642174872562, 2: '111', 3: 111.0}
2022-01-14 18:41:12.575 [main] INFO  com.kaa.simplebuild.DataProviderJDBC - conn0: url=jdbc:h2:tcp://localhost/~/test user=ADMIN
2022-01-14 18:41:12.930 [main] DEBUG com.kaa.simplebuild.DataProviderJDBC - [RoofMaterial{id=1642174872562, name='111', price=111.0}]
2022-01-14 18:41:12.935 [main] DEBUG com.kaa.simplebuild.DataProviderJDBC - [RoofMaterial{id=1642174872562, name='111', price=111.0}]
2022-01-14 18:41:12.935 [main] INFO  com.kaa.simplebuild.DataProviderJDBCTest - create  RoofMaterial{id=1642174872562, name='111', price=111.0}
2022-01-14 19:59:19.225 [main] DEBUG history.NewMain - NewMain()[0]: starting application.........
2022-01-14 19:59:19.639 [main] ERROR com.kaa.simplebuild.DataProviderJDBC - org.h2.jdbc.JdbcSQLSyntaxErrorException: Неверное количество столбцов
Column count does not match; SQL statement:
INSERT INTO ROOFTEMPLATE VALUES (?,?,?,?) [21002-202]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.dml.Insert.prepare(Insert.java:295)
	at org.h2.command.Parser.prepareCommand(Parser.java:971)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:614)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:288)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:190)
	at java.lang.Thread.run(Unknown Source)

2022-01-14 20:00:11.486 [main] DEBUG history.NewMain - NewMain()[0]: starting application.........
2022-01-14 20:00:11.537 [main] ERROR com.kaa.simplebuild.DataProviderJDBC - org.h2.jdbc.JdbcSQLSyntaxErrorException: Неверное количество столбцов
Column count does not match; SQL statement:
INSERT INTO ROOFTEMPLATE VALUES (?,?,?,?,?,?) [21002-202]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.command.dml.Insert.prepare(Insert.java:295)
	at org.h2.command.Parser.prepareCommand(Parser.java:971)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:614)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:288)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:190)
	at java.lang.Thread.run(Unknown Source)

2022-01-14 20:05:23.303 [main] DEBUG history.NewMain - NewMain()[0]: starting application.........
2022-01-14 20:05:23.354 [main] ERROR com.kaa.simplebuild.DataProviderJDBC - org.h2.jdbc.JdbcSQLException: Параметр "#6" не установлен
Parameter "#6" is not set [90012-195]
2022-01-14 20:07:46.935 [main] DEBUG history.NewMain - NewMain()[0]: starting application.........
2022-01-14 20:07:46.987 [main] ERROR com.kaa.simplebuild.DataProviderJDBC - org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Нарушение ссылочной целостности: "CONSTRAINT_36: PUBLIC.ROOFTEMPLATE FOREIGN KEY(ID_MATERIAL) REFERENCES PUBLIC.ROOFMATERIAL(ID) (CAST(1 AS BIGINT))"
Referential integrity constraint violation: "CONSTRAINT_36: PUBLIC.ROOFTEMPLATE FOREIGN KEY(ID_MATERIAL) REFERENCES PUBLIC.ROOFMATERIAL(ID) (CAST(1 AS BIGINT))"; SQL statement:
INSERT INTO ROOFTEMPLATE VALUES (?,?,?,?,?,?) [23506-202]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:311)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:252)
	at org.h2.table.Table.fireConstraints(Table.java:1173)
	at org.h2.table.Table.fireAfterRow(Table.java:1191)
	at org.h2.command.dml.Insert.insertRows(Insert.java:188)
	at org.h2.command.dml.Insert.update(Insert.java:135)
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:61)
	at org.h2.command.CommandContainer.update(CommandContainer.java:173)
	at org.h2.command.Command.executeUpdate(Command.java:247)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:413)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:190)
	at java.lang.Thread.run(Unknown Source)

2022-01-14 20:08:41.898 [main] DEBUG history.NewMain - NewMain()[0]: starting application.........
2022-01-14 23:53:10.541 [main] DEBUG history.NewMain - NewMain()[0]: starting application.........
